### ISSUE TITLE
 error: array must be initialized with a brace-enclosed initializer 

### ISSUE THREAD

**Issue by rashidrafeek** [eth-cscs/SpFFT#26]
The following error came while installing SpFFT while running `make -j8 install`:

```
[PATH]/src/memory/host_array_view.hpp:164:3: error: array must be initialized with a brace-enclosed initializer
   HostArrayView3D() = default;
```

Any info regarding this would be helpful. This occured while installing SpFFT locally in a cluster. I have attached the full output in a file.
[SpFFTmake.log](https://github.com/eth-cscs/SpFFT/files/3896791/SpFFTmake.log)

**Comment by AdhocMan** [comment]
Could provide some details about the C++ compiler you are using?

**Comment by rashidrafeek** [comment]
The C++ compiler used is: (by `c++ --version`)

```
c++ (GCC) 4.8.5 20150623 (Red Hat 4.8.5-36)
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

**Comment by AdhocMan** [comment]
This compiler version does not fully support C++11. The minimum GCC version required is 6.0. As an alternative you can also use Clang (version 5 and later) or ICC (18.0 and later).

**Comment by rashidrafeek** [comment]
Thanks. The issue was solved by changing the C++ compiler to newer local version.
