### ISSUE TITLE
Provide SOVERSION for the shared library

### ISSUE THREAD

**Issue by merkys** [eth-cscs/SpFFT#27]
I am interested in packaging SpFFT for Debian. Debian uses SOVERSIONs to track the ABI changes, therefore there is a requirement for libraries to have one. The simplest way to set a SOVERSION would be to add the following to `CMakeLists.txt`:
```cmake
# set SOVERSION
set_property(TARGET spfft PROPERTY SOVERSION 0)
```
Here the SOVERSION is set to `0`, but could be any version of your choice.

**Comment by AdhocMan** [comment]
Thanks for looking into packing for Debian. 
I've added a `VERSION` and `SOVERSION` property to the library with 3295d814b6cc6d7a65e1e47970a5c0bd7a645a91. There will probably be a new release with this change included next week.

**Comment by merkys** [comment]
Great! Thanks a lot for the prompt fix!
