### ISSUE TITLE
Build/install process does not seem to use CMAKE_INSTALL_LIBDIR

### ISSUE THREAD

**Issue by merkys** [eth-cscs/SpFFT#28]
It seems that `cmake` installs the shared library, cmake and pkgconfig files under `${CMAKE_INSTALL_PREFIX}/lib` regardless the setting of `CMAKE_INSTALL_LIBDIR`.

**Comment by AdhocMan** [comment]
I wasn't yet aware of the `GNUInstallDirs` module of CMake, which provides this variable.
Since the provided default prefixes match the current hard coded ones, this should not change the current default behavior. I've added this feature with 3295d814b6cc6d7a65e1e47970a5c0bd7a645a91.

**Comment by merkys** [comment]
Thanks a lot for the fix!
