### ISSUE TITLE
CMake can't find MLKSequential

### ISSUE THREAD

**Issue by AlexanderMath** [eth-cscs/SpFFT#41]
Reproduce: just run code below in https://colab.research.google.com/ (ubuntu terminal through browser).

```
!apt-get install -y fftw3
!git clone https://github.com/eth-cscs/SpFFT
%cd SpFFT
%mkdir build
%cd build
!cmake .. -DSPFFT_OMP=ON -DSPFFT_MPI=ON -DSPFFT_GPU_BACKEND=CUDA -DSPFFT_SINGLE_PRECISION=OFF -DCMAKE_INSTALL_PREFIX=/usr/loca
```

Everything seems to work fine, except MLKSequential. Does anyone have any suggestions for how to fix this?

![image](https://user-images.githubusercontent.com/8614529/106341389-617e8080-629d-11eb-946c-cf1a811c1596.png)

**Comment by AlexanderMath** [comment]
Ahh, sorry, I'm getting tired. The error was due to FFTW and not MLKSequential, the following fixed the error. 

```
!sudo apt-get install libfftw3-dev libfftw3-do
!git clone https://github.com/eth-cscs/SpFFT
%cd SpFFT
%mkdir build
%cd build
!cmake .. -DSPFFT_OMP=ON -DSPFFT_MPI=ON -DSPFFT_GPU_BACKEND=CUDA -DSPFFT_SINGLE_PRECISION=OFF -DCMAKE_INSTALL_PREFIX=/usr/local
```

**Comment by AdhocMan** [comment]
It looks like you are using Ubuntu, for which the default search path of CMake usually works. So my first suggestion would be, to check where the library is actually located. In Ubuntu 20.04, the library should be in `/usr/lib/x86_64-linux-gnu` and the header file in `/usr/include`.  Alternatively, use a search command like `find /usr -name "libfftw3*"` and `find /usr -name "fftw3.h"`.
If you located the library and header file, you can try to tell CMake to search in additional locations through the `CMAKE_PREFIX_PATH` variable with a semicolon separated list of directories. For example `-DCMAKE_PREFIX_PATH="/usr/lib/x86_64-linux-gnu;/usr/include"`
