### ISSUE TITLE
SpFFT fails to find MPI with Cray wrappers on Alps

### ISSUE THREAD

**Issue by lucamar** [eth-cscs/SpFFT#49]
Hi,
I could not configure properly SpFFT release 1.0.4 with the flag `-DSPFFT_MPI=ON` on the Alps system (production partition: Eiger). I load the default `CMake` (3.20.1), `cpeGNU/21.06` and `cray-fftw`, then I configure as follows: 
```
cmake ../SpFFT-1.0.4 -DCMAKE_BUILD_TYPE=RELEASE -DSPFFT_FFTW_LIB=FFTW -DSPFFT_SINGLE_PRECISION=ON -DSPFFT_MPI=ON -DSPFFT_OMP=ON
-- The CXX compiler identification is GNU 10.3.0
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /opt/gcc/10.3.0/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Could NOT find MPI_CXX (missing: MPI_CXX_LIB_NAMES MPI_CXX_HEADER_DIR MPI_CXX_WORKS)
CMake Error at /apps/eiger/UES/jenkins/1.4.0/software/CMake/3.20.1/share/cmake-3.20/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find MPI (missing: MPI_CXX_FOUND CXX)
Call Stack (most recent call first):
  /apps/eiger/UES/jenkins/1.4.0/software/CMake/3.20.1/share/cmake-3.20/Modules/FindPackageHandleStandardArgs.cmake:594 (_FPHSA_FAILURE_MESSAGE)
  /apps/eiger/UES/jenkins/1.4.0/software/CMake/3.20.1/share/cmake-3.20/Modules/FindMPI.cmake:1742 (find_package_handle_standard_args)
  CMakeLists.txt:156 (find_package)

-- Configuring incomplete, errors occurred!
```

Even manually defining the following variables does not change the configure error:
```
-DMPI_CXX_COMPILER=/opt/cray/pe/craype/2.7.8/bin/CC 
-DMPI_CXX_COMPILER_INCLUDE_DIRS=/opt/cray/pe/mpich/8.1.6/ofi/gnu/9.1/include/
-DMPI_CXX_HEADER_DIR=/opt/cray/pe/mpich/8.1.6/ofi/gnu/9.1/include
```

Any advice would be very much appreciated!

**Comment by AdhocMan** [comment]
With CMake on Cray systems, MPI is usually only found if it recognizes the Cray environment. To do so, you need to set the language compilers to the cray wrappers. Just setting the MPI compiler is sadly not enough.
To compile on Eiger, you could try:
1. Clear the build folder
2. `CXX=CC CC=cc FC=ftn cmake ../SpFFT-1.0.4 -DCMAKE_BUILD_TYPE=RELEASE -DSPFFT_FFTW_LIB=FFTW -DSPFFT_SINGLE_PRECISION=ON -DSPFFT_MPI=ON -DSPFFT_OMP=ON`

**Comment by lucamar** [comment]
Thanks for the advice @AdhocMan: I already had the definition of the wrappers in the environment, but apparently it was not caught by CMake. Adding them as well in the configure line solved the issue, thanks again.
