### ISSUE TITLE
`device_synchronize()` always ON on AMD

### ISSUE THREAD

**Issue by gsavva** [eth-cscs/SpFFT#53]
When compiling for AMD execution in `Release` mode, the `device_synchronize` is still active which causes overheads (issue found in while profiling SIRIUS, a tracing snapshot is attached at the end).

More specifically, the `#ifndef NDEBUG` block [before](https://github.com/eth-cscs/SpFFT/blob/master/src/gpu_util/gpu_runtime.hpp#L62-L65) and [after](https://github.com/eth-cscs/SpFFT/blob/master/src/gpu_util/gpu_runtime.hpp#L68-L71) the kernel launch is **always** executed.

`device_synchronize()` is not present when compiled with `CUDA` in `Release` mode.

This is because the corresponding HIP_FLAGS are missing, where for CUDA, they are explicitly defined in the [CMAKE](https://github.com/eth-cscs/SpFFT/blob/master/CMakeLists.txt#L28-L40)

![image](https://github.com/eth-cscs/SpFFT/assets/41191161/3f376859-2651-4248-8ae9-2b401403bf14)

**Comment by AdhocMan** [comment]
Thanks for reporting this. I'll look into a fix.
Until then, you can add the macro definition to the `HIP_HCC_FLAGS` CMake variable together with the architecture flags. So something like `-DHIP_HCC_FLAGS="-DNDEBUG --offload-arch=gfx906"`.

**Comment by AdhocMan** [comment]
This should now be fixed by #54.
Note that the CMake HIP language feature is now being used, so `HIP_HCC_FLAGS` will no longer have any effect.
